name: trigger action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 22f3000147@ds.study.iitm.ac.in
        run: echo "Hello, this step has my email!"
